### ISSUE TITLE
OpenGL error when run the script run_main.py to visualize default plys

### ISSUE THREAD

**Issue by laliwang** [Florian-Barthel/splatviz#21]
Thanks sincerely for your excellent share and projects! While I have create the conda environment just follow your instructions exactly, some errors interrupt when I just run the script run_main.py as follows:
Could you please provide some advice for this error? Thanks a lot!
```
Traceback (most recent call last):
  File "/code1/wjh/Lang3DGS/Visers/splatviz/run_main.py", line 232, in <module>
    main()
  File "/code1/wjh/anaconda3/envs/gs-view/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/code1/wjh/anaconda3/envs/gs-view/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/code1/wjh/anaconda3/envs/gs-view/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/code1/wjh/anaconda3/envs/gs-view/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/code1/wjh/Lang3DGS/Visers/splatviz/run_main.py", line 225, in main
    viz = Visualizer(data_path=data_path, use_gan_decoder=use_decoder)
  File "/code1/wjh/Lang3DGS/Visers/splatviz/run_main.py", line 39, in __init__
    super().__init__(title="splatviz", window_width=1920, window_height=1080, font=self.regular_font_path, code_font=self.code_font_path)
  File "/code1/wjh/Lang3DGS/Visers/splatviz/gui_utils/imgui_window.py", line 46, in __init__
    self._imgui_renderer = _GlfwRenderer(self._glfw_window)
  File "/code1/wjh/Lang3DGS/Visers/splatviz/gui_utils/imgui_window.py", line 113, in __init__
    super().__init__(*args, **kwargs)
  File "/code1/wjh/anaconda3/envs/gs-view/lib/python3.10/site-packages/imgui_bundle/python_backends/glfw_backend.py", line 20, in __init__
    super(GlfwRenderer, self).__init__()
  File "/code1/wjh/anaconda3/envs/gs-view/lib/python3.10/site-packages/imgui_bundle/python_backends/opengl_backend.py", line 61, in __init__
    super(ProgrammablePipelineRenderer, self).__init__()
  File "/code1/wjh/anaconda3/envs/gs-view/lib/python3.10/site-packages/imgui_bundle/python_backends/base_backend.py", line 17, in __init__
    self._create_device_objects()
  File "/code1/wjh/anaconda3/envs/gs-view/lib/python3.10/site-packages/imgui_bundle/python_backends/opengl_backend.py", line 123, in _create_device_objects
    self._attrib_location_tex = gl.glGetUniformLocation(
  File "/code1/wjh/anaconda3/envs/gs-view/lib/python3.10/site-packages/OpenGL/latebind.py", line 63, in __call__
    return self.wrapperFunction( self.baseFunction, *args, **named )
  File "/code1/wjh/anaconda3/envs/gs-view/lib/python3.10/site-packages/OpenGL/GL/VERSION/GL_2_0.py", line 430, in glGetUniformLocation
    return baseOperation( program, name )
  File "/code1/wjh/anaconda3/envs/gs-view/lib/python3.10/site-packages/OpenGL/platform/baseplatform.py", line 415, in __call__
    return self( *args, **named )
  File "/code1/wjh/anaconda3/envs/gs-view/lib/python3.10/site-packages/OpenGL/error.py", line 230, in glCheckError
    raise self._errorClass(
OpenGL.error.GLError: GLError(
	err = 1282,
	description = b'invalid operation',
	baseOperation = glGetUniformLocation,
	cArguments = (1, b'Texture\x00'),
	result = -1
)
```

**Comment by laliwang** [comment]
I have solved this through `export MESA_GL_VERSION_OVERRIDE=3.3` before `python run_main.py`.
