### ISSUE TITLE
OpenGL.error.Error: Attempt to retrieve context when no valid context

### ISSUE THREAD

**Issue by mini-full** [Florian-Barthel/splatviz#34]
Running on a Ubuntu server without a physical monitor.
I have tried add data_path, but it's not working.
Does that need a monitor to work?

Also I am wondering are there any other python tools(not necessarily with a viewer) that can edit gaussian splat results, like combining 2 gaussian point clouds into one with specified relative poses?

Traceback (most recent call last):
  File "wkx/splatviz/run_main.py", line 233, in <module>
    main()
  File "/home/wkx/anaconda3/envs/gs-view/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/wkx/anaconda3/envs/gs-view/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/wkx/anaconda3/envs/gs-view/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/wkx/anaconda3/envs/gs-view/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "wkx/splatviz/run_main.py", line 226, in main
    viz = Visualizer(data_path=data_path, use_gan_decoder=use_decoder)
  File "splatviz/run_main.py", line 39, in __init__
    super().__init__(title="splatviz", window_width=1920, window_height=1080, font=self.regular_font_path, code_font=self.code_font_path)
  File "wkx/splatviz/gui_utils/imgui_window.py", line 46, in __init__
    self._imgui_renderer = _GlfwRenderer(self._glfw_window)
  File "wkx/splatviz/gui_utils/imgui_window.py", line 113, in __init__
    super().__init__(*args, **kwargs)
  File "/home/wkx/anaconda3/envs/gs-view/lib/python3.10/site-packages/imgui_bundle/python_backends/glfw_backend.py", line 20, in __init__
    super(GlfwRenderer, self).__init__()
  File "/home/wkx/anaconda3/envs/gs-view/lib/python3.10/site-packages/imgui_bundle/python_backends/opengl_backend.py", line 61, in __init__
    super(ProgrammablePipelineRenderer, self).__init__()
  File "/home/wkx/anaconda3/envs/gs-view/lib/python3.10/site-packages/imgui_bundle/python_backends/base_backend.py", line 17, in __init__
    self._create_device_objects()
  File "/home/wkx/anaconda3/envs/gs-view/lib/python3.10/site-packages/imgui_bundle/python_backends/opengl_backend.py", line 146, in _create_device_objects
    gl.glVertexAttribPointer(
  File "/home/wkx/anaconda3/envs/gs-view/lib/python3.10/site-packages/OpenGL/latebind.py", line 63, in __call__
    return self.wrapperFunction( self.baseFunction, *args, **named )
  File "/home/wkx/anaconda3/envs/gs-view/lib/python3.10/site-packages/OpenGL/GL/VERSION/GL_2_0.py", line 469, in glVertexAttribPointer
    contextdata.setValue( key, array )
  File "/home/wkx/anaconda3/envs/gs-view/lib/python3.10/site-packages/OpenGL/contextdata.py", line 58, in setValue
    context = getContext( context )
  File "/home/wkx/anaconda3/envs/gs-view/lib/python3.10/site-packages/OpenGL/contextdata.py", line 40, in getContext
    raise error.Error(
OpenGL.error.Error: Attempt to retrieve context when no valid context

**Comment by Florian-Barthel** [comment]
> Running on a Ubuntu server without a physical monitor. I have tried add data_path, but it's not working. Does that need a monitor to work?

Yes the viewer requires a Monitor. There are plans in the future to have the rendering on a server but currently it has to render and display the results on the same machine.

> Also I am wondering are there any other python tools(not necessarily with a viewer) that can edit gaussian splat results, like combining 2 gaussian point clouds into one with specified relative poses?

I am currently not aware of any other python tools that allow editing of 3DGS scenes. Supersplat is a web viewer that allows some editing, however, its not in python and the rendering is quiet slow for large scenes.

**Comment by mini-full** [comment]
OK Thank you for your answer. I have switched to a local machine and ran it without trouble.
