### ISSUE TITLE
OSError: exception: access violation reading 0x000000CAC99F0000 & TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by brisyramshere** [Florian-Barthel/splatviz#48]
我运行run_main.py报以下错误，请问是什么原因？

`Traceback (most recent call last):
  File "D:\ProgramData\anaconda3\envs\nerfstudio\lib\site-packages\OpenGL\latebind.py", line 41, in __call__
    return self._finalCall( *args, **named )
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Proj\NeuroRender\splatviz\run_main.py", line 19, in <module>
    main()
  File "D:\ProgramData\anaconda3\envs\nerfstudio\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "D:\ProgramData\anaconda3\envs\nerfstudio\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "D:\ProgramData\anaconda3\envs\nerfstudio\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\ProgramData\anaconda3\envs\nerfstudio\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\Proj\NeuroRender\splatviz\run_main.py", line 12, in main
    splatviz = Splatviz(data_path=data_path, mode=mode, host=host, port=port, ggd_path=ggd_path)
  File "D:\Proj\NeuroRender\splatviz\splatviz.py", line 40, in __init__
    super().__init__(
  File "D:\Proj\NeuroRender\splatviz\splatviz_utils\gui_utils\imgui_window.py", line 46, in __init__
    self._imgui_renderer = _GlfwRenderer(self._glfw_window)
  File "D:\Proj\NeuroRender\splatviz\splatviz_utils\gui_utils\imgui_window.py", line 112, in __init__
    super().__init__(*args, **kwargs)
  File "D:\ProgramData\anaconda3\envs\nerfstudio\lib\site-packages\imgui_bundle\python_backends\glfw_backend.py", line 20, in __init__
    super(GlfwRenderer, self).__init__()
  File "D:\ProgramData\anaconda3\envs\nerfstudio\lib\site-packages\imgui_bundle\python_backends\opengl_backend.py", line 61, in __init__
    super(ProgrammablePipelineRenderer, self).__init__()
  File "D:\ProgramData\anaconda3\envs\nerfstudio\lib\site-packages\imgui_bundle\python_backends\base_backend.py", line 18, in __init__
    self.refresh_font_texture()
  File "D:\ProgramData\anaconda3\envs\nerfstudio\lib\site-packages\imgui_bundle\python_backends\opengl_backend.py", line 81, in refresh_font_texture
    gl.glTexImage2D(
  File "D:\ProgramData\anaconda3\envs\nerfstudio\lib\site-packages\OpenGL\latebind.py", line 45, in __call__
    return self._finalCall( *args, **named )
  File "D:\ProgramData\anaconda3\envs\nerfstudio\lib\site-packages\OpenGL\wrapper.py", line 868, in wrapperCall
    result = wrappedOperation( *cArguments )
OSError: exception: access violation reading 0x000000CAC99F0000`

**Comment by Florian-Barthel** [comment]
If this is still an issue, please explain what you do to get this error
