### ISSUE TITLE
Error creating conda environment 

### ISSUE THREAD

**Issue by oo0o00oo0** [Florian-Barthel/splatviz#49]
I have recursively cloned the repo however when I run `conda env create -f environment.yml` I get:

`Building wheels for collected packages: diff_gauss, simple_knn
  Building wheel for diff_gauss (setup.py): started
  Building wheel for diff_gauss (setup.py): finished with status 'error'
  Running setup.py clean for diff_gauss
  Building wheel for simple_knn (setup.py): started
  Building wheel for simple_knn (setup.py): finished with status 'error'
  Running setup.py clean for simple_knn
Failed to build diff_gauss simple_knn

Pip subprocess error:
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      running bdist_wheel
      C:\Users\inter\anaconda3\envs\gs-view\lib\site-packages\torch\utils\cpp_extension.py:499: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
        warnings.warn(msg.format('we could not find ninja.'))
      running build
      running build_py
      creating build\lib.win-amd64-cpython-310\diff_gauss
      copying diff_gauss\__init__.py -> build\lib.win-amd64-cpython-310\diff_gauss
      running build_ext
      error: [WinError 2] The system cannot find the file specified
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for diff_gauss
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      running bdist_wheel
      C:\Users\inter\anaconda3\envs\gs-view\lib\site-packages\torch\utils\cpp_extension.py:499: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
        warnings.warn(msg.format('we could not find ninja.'))
      running build
      running build_ext
      error: [WinError 2] The system cannot find the file specified
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for simple_knn
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (diff_gauss, simple_knn)

failed

CondaEnvException: Pip failed`

I then add ninja and get this:

>python run_main.py
Traceback (most recent call last):
  File "XXX\splatviz\run_main.py", line 2, in <module>
    from splatviz import Splatviz
  File "XXX\splatviz\splatviz.py", line 11, in <module>
    from renderer.gaussian_renderer import GaussianRenderer
  File "XXX\splatviz\renderer\gaussian_renderer.py", line 12, in <module>
    from compression.compression_exp import run_single_decompression
  File "XXX\splatviz\compression\compression_exp.py", line 4, in <module>
    from scene import GaussianModel
  File "XXX\splatviz\./gaussian-splatting\scene\__init__.py", line 16, in <module>
    from scene.dataset_readers import sceneLoadTypeCallbacks
  File "XXX\splatviz\./gaussian-splatting\scene\dataset_readers.py", line 24, in <module>
    from scene.gaussian_model import BasicPointCloud
  File "XXX\splatviz\./gaussian-splatting\scene\gaussian_model.py", line 20, in <module>
    from simple_knn._C import distCUDA2
ModuleNotFoundError: No module named 'simple_knn'

**Comment by Florian-Barthel** [comment]
Now that you have installed ninja manually you can try to install the simple_knn submodule again:
run: "pip install gaussian-splatting/submodules/simple-knn" in the root folder of splatviz.

You might have to install other pip dependencies aswell, as the installation did not finish:
    - gaussian-splatting/submodules/diff-gaussian-rasterization
    - imgui_bundle==1.5.2
    - imgui==2.0.0
    - scikit-image==0.24
    - imagecodecs[all]==2024.6.1
    - pynvml
    - GPUtil
